OPENROUTER_API_KEY: "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"
MODEL: "deepseek/deepseek-chat-v3.1:free"

# Optional: adjust max_tokens if you want longer responses
MAX_TOKENS: 2000
